server:
  port: 8081

spring:
  application:
    name: user-service
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

logging:
  level:
    org.springframework.security: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://@eureka-service-host@:8761/eureka

