server:
  port: 18080
  context-path: /uaa

spring:
  application:
    name: authorization



eureka:
  client:
    serviceUrl:
      defaultZone: http://@eureka-service-host@:8761/eureka
#      defaultZone: http://eureka:8761/eureka
#      defaultZone: http://localhost:8761/eureka
